services:
  yourls:
    build: .
    container_name: 'fracz-pl'
    restart: always
    environment:
      - YOURLS_SITE=https://fracz.com
      - YOURLS_USER=${YOURLS_USER}
      - YOURLS_PASS=${YOURLS_PASS}
      - YOURLS_DB_PASS=${YOURLS_DB_PASS}
      - YOURLS_DB_HOST=${YOURLS_DB_HOST:-mysqldb}
      - YOURLS_DB_USER=${YOURLS_DB_USER:-yourls}
      - YOURLS_DB_NAME=${YOURLS_DB_NAME:-yourls}
    volumes:
      - ./uploads:/var/www/html/uploads:z
      - ../temp:/var/www/temp:z

  gitea:
    image: docker.gitea.com/gitea:1.26.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=${GITEA_DB_HOST}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    restart: always
    networks:
      - webproxy
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT}:22"

networks:
  default:
    external:
      name: webproxy
