version: '3'

services:
  site:
    container_name: fracz-pl
    build: docker
    restart: unless-stopped
    networks: [default, proxy]
#    ports:
#      - "1234:80"
    environment:
      VIRTUAL_HOST: fracz.pl,www.fracz.pl,fracz.com,www.fracz.com
      LETSENCRYPT_HOST: fracz.pl,www.fracz.pl,fracz.com,www.fracz.com
      LETSENCRYPT_EMAIL: fraczwojciech@gmail.com
    expose: [80]
    volumes:
      - ./yourls:/var/www/html:z

  site-db:
    container_name: fracz-pl-db
    restart: unless-stopped
    image: mysql
    networks: [default, dbnetwork]
    environment:
      MYSQL_ROOT_PASSWORD: X2UVxX9dTJ6
      MYSQL_DATABASE: site
      MYSQL_USER: fracz
      MYSQL_PASSWORD: X2UVxX9dTJ6
    volumes:
       - ./var/mysql:/var/lib/mysql:z

networks:
  proxy:
    external:
      name: webproxy
  dbnetwork:
    external: true
