services:
  mariadb-backup:
    build: .
    volumes:
      - ./config.yml:/app/config.yml:ro
      - /var/tmp/mariadb-backups:/tmp/mariadb-backups
      - ./rclone:/config/rclone
    environment:
      TZ: Europe/Warsaw
      RCLONE_CONFIG: /config/rclone/rclone.conf
    command: ["/app/config.yml"]
    restart: "no"
